language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
cache:
  directories:
    - $HOME/libsodium
before_install:
  - sudo ./.travis-libsodium.sh
install:
  - pip install -r requirements.txt
  - pip install 'pytest-cov>=2.4.0,<2.6'
  - pip install codecov
script:
  - pytest --cov=./
after_success:
  - codecov